<?php
if(!isset($_SESSION["lang"]))
$_SESSION["lang"]="ar";
if(isset($_GET["lang"]))
$_SESSION["lang"]=$_GET["lang"];




$lang='
{
    "en":{
"style":"",
"test":"translation",
"test2":"translation2",
"otherservices":"Other Services",
"Send Email Message":"Send Email Message",
"Service Requests":"Service Requests",
"View Services":"Services",
"home":"Home",
"Dashboard":"Dashboard",
"Type your message here":"Type your message here",
"SEND":"SEND",
"USERS":"USERS",
"All Users Listed":"All Users Listed",
"Enter name to search":"Enter name or email to search",
"Category Request":"Request to join the providers team",
"Categories Management":"Categories Management",
"main categories":"main categories",
"subcategories under":"subcategories under",
"sub categories":"sub categories",
"Enter new category name":"Enter new category name",
"Enter new category description":"Enter new category description",
"delete":"delete",
"update":"update",
"Add new":"Add ",
"Edit your services":"Edit your services",
"Enter title":"Enter title",
"Description":"Description",
"Advantages":"Advantages",
"Select Image Files for your Service":"Select maximum 10 Images for your Service",
"Categories":"Categories",
"Type a message here":"Type a message here",
"LOGIN":"LOGIN",
"log into your account":"log into your account",
"Enter Email Here":"Enter Email Here",
"Enter your password":"Enter your password",
"or you can sign up":"or you can sign up",
"Profile":"Profile",
"Purchased Services":"Purchased Services",
"Points":"Points",
"Email address":"Email address",
"Contact information":"Contact information",
"Address":"Address",
"City":"City",
"Postal code":"Postal code",
"About me":"About me",
"UPDATE YOUR INFORMAITION":"UPDATE YOUR INFORMAITION",
"category":"category",
"Select an user to start chat":"Select an user to start chat",
"Users Chat":"Users Chat",
"Providers list":"Providers list",
"sold Services":"sold Services",
"Provider Requests":"Provider Requests",
"Service Informations":"Service Informations",
"EDIT":"EDIT",
"SIGN UP":"SIGN UP",
"Email and Password Confirmation":"Email and Password Confirmation",
"Confirm Email":"Confirm Email",
"Confirm Password":"Confirm Password",
"Select category":"Select category",
"personal information":"personal information",
"First Name":"First Name",
"Last Name":"Last Name",
"Phone No":"Phone No",
"Optional informations":"Optional informations",
"Second Phone No":"Second Phone No",
"Does Not Match":"Does Not Match",
"At least 8 characters with at least 2 numericals":"At least 8 characters with at least 2 numericals",
"Please provide a valid email":"Please provide a valid email",
"valid data":"The Above Informations Must be Filled by a valid data",
"Upload":"UPLOAD",
"Update Profile":"Update Profile",
"YES":"YES",
"NO":"NO",
"Upload Service":"Upload Service",
"Dashboard Shortcuts":"Dashboard Shortcuts",
"Manage Services":"Manage Services",
"USER":"USER",
"SERVICES":"SERVICES",
"LOGOUT":"LOGOUT",
"SERVICE btn PROVIDER":"SERVICE<br>PROVIDER",
"Suggestions":"Suggestions",
"Edit Service":"Edit Service",
"All providers Listed":"Providers",
"deactive_cat":"Deactivate",
"active_cat":"Active",
"service_setting":"Control Services",
"must select":"Must Select One Of The Above",
"at least 3 pics":"You have to insert 3 pictures at least",
"status":"Status",
"pending approval":"pending approval",
"active":"active",
"blockced":"blocked",
"setting":"Setting",
"provider":"Provider",
"LINKS":"LINKS",
"Password":"Password",
"id":"ID",
"Role":"Role",
"admin":"Admin",
"normal":"Normal",
"HAREEF":"HAREEF"
    },
    
    "ar":{
"style":"p,h4,h5,h6,textarea,input,select{direction: rtl;text-align:right;}",
"test":"ترجمه",
"test2":"ترجمه2",
"otherservices":"خدمات اخرى",
"Send Email Message":"ارسل رسالة عبر البريد الإلكتروني",
"Service Requests":"طلبات الخدمات",
"View Services":"الخدمات",
"home":"الصفحة الرئيسية"    ,
"Dashboard":"لوحة التحكم",
"Type your message here":"اكتب رسالتك هنا",
"SEND":"إرسال",
"USERS":"المستخدمين",
"All Users Listed":"جميع المستخدمين",
"Enter name to search":"ادخل اسم, بريد الكرتوني للبحث",
"Category Request":"طلبات الانضمام الى فريق مزودين الخدمات",
"Categories Management":"ادارة التصنيفات",
"main categories":"التصنيف الرئيسي",
"subcategories under":"تصنيف فرعي من",
"sub categories":"تصنيف فرعي",
"Enter new category name":"ادخل اسم تصنيف جديد",
"delete":"حذف",
"update":"تعديل",
"Enter new category description":"ادخل وصف للتصنيف الجديد",
"Add new":"اضافة  ",
"Edit your services":"تعديل بيانات الخدمه",
"Enter title":"ادخل عنوان",
"Description":"وصف",
"Advantages":"ميزات",
"Select Image Files for your Service":"يرجى اختيار 10 صور كحد اقصى لخدمتك",
"Categories":"تصنيفات",
"Type a message here":"اكتب رسالتك هنا",
"LOGIN":"تسجيل الدخول",
"log into your account":"تسجل الدخول الى حسابك الخاص",
"Enter Email Here":"اكتب بريدك الالكتروني هنا",
"Enter your password":"ادخل كلمة السر",
"or you can sign up":"أو بامكانك تسجيلل حساب جديد",
"Profile":"الحساب الشخصي",
"Purchased Services":"الخدمات المبتعاه",
"Points":"النقاط",
"Email address":"البريد الالكتروني",
"Contact information":"معلومات الاتصال",
"Address":"العنوان",
"City":"المدينه",
"Postal code":"الرمز البريدي",
"About me":"نبذه عني",
"UPDATE YOUR INFORMAITION":"تعديل بيانتك الشخصيه",
"category":"التصنيف",
"Select an user to start chat":"اختر احد المستخدمين لتبدأ المحادثه",
"Users Chat":"المحادثات",
"Providers list":"مزودين الخدمه",
"sold Services":"الخدمات المباعه",
"Provider Requests":"طلبات الانضمام الى فريق مزودين الخدمه",
"Service Informations":"معلومات عن الخدمه",
"EDIT":"تعديل",
"SIGN UP":"تسجيل حساب جديد",
"Email and Password Confirmation":"تأكيد البريد الالكتروني و كلمة السر",
"Confirm Email":"تأكيد البريد الالكتروني",
"Confirm Password":"تأكيد كلمة السر",
"Select category":"يجب اختيار احد التصنيفات التاليه",
"personal information":"المعلومات الشخصيه",
"First Name":"الاسم الاول",
"Last Name":"اسم العائله",
"Phone No":"رقم الهاتف",
"Optional informations":"حقول اختياريه",
"Second Phone No":"رقم هاتف بديل",
"Does Not Match":"غير متطابق",
"At least 8 characters with at least 2 numericals":"يجب ان تتكون كلمة السر من 8 احرف على الاقل يتضمنهم رقمان",
"Please provide a valid email":"يرجى كتابة صيغة صحيحة للبريد الألكتروني",
"valid data":"المعلومات اعلاه يجب ان تتصمن مدخلات صحيحه",
"Upload":"رفع",
"Update Profile":"تعديل بيانات الحساب الشخصي",
"YES":"نعم",
"NO":"لا",
"Upload Service":"اضافة خدمة الى النظام",
"Dashboard Shortcuts":"اختصارت الشاشة الرئيسية",
"Manage Services":"ادارة الخدمات",
"USER":"مستخدم",
"SERVICES":"الخدمات",
"LOGOUT":"تسجيل الخروج",
"SERVICE btn PROVIDER":"مقدم<br>خدمه",
"Suggestions":"اقراحات",
"Edit Service":"تعديل الخدمه",
"All providers Listed":"مقدمين الخدمات",
"deactive_cat":"إيقاف",
"active_cat":"تفعيل",
"service_setting":"التحكم بالخدمات",
"must select":"يجب إختيار احد الخيارات اعلاه",
"at least 3 pics":"يجب إدراج 3 صور على الأقل",
"status":"الحاله",
"pending approval":"بانتضار الموافقه",
"active":"مفعل",
"blockced":"متوقف",
"setting":"اعدادات",
"provider":"مقدم خدمه",
"LINKS":"الوصول السريع",
"Password":"كلمة السر",
"id":"الرقم المعرف",
"Role":"نوع المستخدم",
"admin":"مشرف",
"normal":"مستخدم",
"HAREEF":"حريف"

    }
}
';

$lang=json_decode($lang);
$key=$_SESSION["lang"];
$lang=$lang->$key;

function tr($key)
{
    global $lang;
    if(isset($lang->$key)){
        //echo $lang->$key;
        return $lang->$key;
    }
    else echo $lang->not_been_added_yet;
}

?>
<style>
    <?php //echo tr("style") ?>
</style>